import Head from "next/head"
import ListUsers from "../components/ListUsers"
import styles from "../styles/Home.module.css"
import Nav from "../components/nav/Nav"
import NavMobile from "../components/nav/NavMobile"

export default function Home() {
  return (
    <div className={styles["home-container"]}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@600;800&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Nav />
      <NavMobile />
      <main className={styles.main}>
        <ListUsers />
      </main>
    </div>
  )
}
