import Head from "next/head"
import ListUsers from "../components/ListUsers"
import styles from "../styles/Home.module.css"
import Nav from "../components/Nav"

export default function Home() {
  return (
    <div className={styles["home-container"]}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className={styles.main}>
        <ListUsers />
      </main>
    </div>
  )
}
